### ISSUE TITLE
GitHub Auto Deployment

### ISSUE THREAD

**Issue by pwyq** [pwyq/Fill-Game#11]

**Comment by pwyq** [comment]
https://gist.github.com/NickNaso/0d478f1481686d5bcc868cac06620a60

**Comment by pwyq** [comment]
oh duck, I realize it requires github token. Sam probably can't do this one

**Comment by Samarium150** [comment]
> oh duck, I realize it requires github token. Sam probably can't do this one

`${{ secrets.GITHUB_TOKEN }}` is an environment secret. I don't have to ask your permission.

**Comment by pwyq** [comment]
Thanks, I just realized it.
