### ISSUE TITLE
Parsing or Gtest bug?

### ISSUE THREAD

**Issue by pwyq** [pwyq/Fill-Game#65]
Weird bug

This function parse gtest name to integer index, e.g. `SIMPLE_16` becomes 16.
https://github.com/pwyq/Fill-Game/blob/a2ac85ff7aa1b29ca2d2fcae080a15afc942ac2b/test/algorithm_test_cases.h#L34

Not working for the following:

https://github.com/pwyq/Fill-Game/blob/a2ac85ff7aa1b29ca2d2fcae080a15afc942ac2b/test/minimax_alphabeta_tt_test.h#L176

https://github.com/pwyq/Fill-Game/blob/a2ac85ff7aa1b29ca2d2fcae080a15afc942ac2b/test/minimax_alphabeta_tt_test.h#L194

https://github.com/pwyq/Fill-Game/blob/a2ac85ff7aa1b29ca2d2fcae080a15afc942ac2b/test/negamax_alphabeta_tt_test.h#L175

https://github.com/pwyq/Fill-Game/blob/a2ac85ff7aa1b29ca2d2fcae080a15afc942ac2b/test/negamax_alphabeta_tt_test.h#L191

**Comment by Samarium150** [comment]
Mine work fine.
![image](https://user-images.githubusercontent.com/28302241/229642755-d40fff39-293d-4699-8a71-f8241da3d8f5.png)
